# Generated by Django 5.0 on 2024-03-21 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_store_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('is_open', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stores.store')),
            ],
        ),
    ]
