# Generated by Django 5.0 on 2024-03-21 07:40

import django.db.models.deletion
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_user_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ForeignKey(default=users.models.get_default_group, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='custom_user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
    ]
